# Generated by Django 4.2.16 on 2025-07-21 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('lstm', 'LSTM'), ('cnn', 'CNN'), ('decision_tree', 'Árbol de Decisiones'), ('transformer', 'Transformer'), ('random_forest', 'Random Forest'), ('xgboost', 'XGBoost')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predictor_columns', models.JSONField(default=list)),
                ('target_columns', models.JSONField(default=list)),
                ('normalization_method', models.CharField(choices=[('min_max', 'Min-Max'), ('standard', 'Estandarización'), ('robust', 'Robust Scaler'), ('none', 'Sin normalización')], default='min_max', max_length=50)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('train_split', models.FloatField(default=0.7)),
                ('val_split', models.FloatField(default=0.15)),
                ('test_split', models.FloatField(default=0.15)),
                ('selected_metrics', models.JSONField(default=list)),
                ('training_history', models.JSONField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_trainer.dataset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('predictions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_trainer.trainingsession')),
            ],
            options={
                'unique_together': {('training_session', 'prediction_date', 'latitude', 'longitude')},
            },
        ),
    ]
