# Generated by Django 4.2.16 on 2025-07-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainer', '0002_add_parent_dataset_name'),
        ('ml_trainer', '0004_remove_dataset_description_dataset_long_description_and_more'),
    ]

    operations = [
    ]
