# Generated by Django 4.2.16 on 2025-07-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainer', '0003_add_root_dataset_id'),
        ('ml_trainer', '0005_merge_20250727_1759'),
    ]

    operations = [
    ]
