# Generated by Django 4.2.16 on 2025-07-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainer', '0004_add_project_model'),
        ('ml_trainer', '0006_merge_20250727_1817'),
    ]

    operations = [
    ]
