# Generated by Django 4.2.16 on 2025-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainer', '0011_remove_dataset_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldefinition',
            name='code_version',
            field=models.IntegerField(default=1, help_text='Version of the exported code'),
        ),
        migrations.AddField(
            model_name='modeldefinition',
            name='exported_code',
            field=models.TextField(blank=True, help_text='Last exported Python code', null=True),
        ),
        migrations.AddField(
            model_name='modeldefinition',
            name='framework',
            field=models.CharField(choices=[('keras', 'TensorFlow/Keras'), ('pytorch', 'PyTorch'), ('sklearn', 'Scikit-learn')], default='keras', help_text='Deep learning framework to use', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='framework',
            field=models.CharField(choices=[('keras', 'TensorFlow/Keras'), ('pytorch', 'PyTorch'), ('sklearn', 'Scikit-learn')], default='keras', max_length=20),
        ),
    ]
