# Generated by Django 4.2.16 on 2025-08-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainer', '0014_add_user_fields_nullable'),
        ('ml_trainer', '0014_add_user_to_weatherprediction'),
    ]

    operations = [
    ]
