# Generated by Django 4.2.16 on 2025-08-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainer', '0015_fix_root_dataset_ids'),
        ('ml_trainer', '0015_merge_20250808_1956'),
    ]

    operations = [
    ]
