# Generated by Django 4.2.16 on 2025-08-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_trainer', '0023_add_preprocessing_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='normalizationchainstep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='normalizationchainstep',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='normalization_chain',
        ),
        migrations.DeleteModel(
            name='NormalizationChain',
        ),
        migrations.DeleteModel(
            name='NormalizationChainStep',
        ),
    ]
